# Generated by Django 2.2.15 on 2020-08-31 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_auto_20200831_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='email',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cv',
            name='mobile_number',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cv',
            name='website',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
