# Generated by Django 2.2.15 on 2020-08-31 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_auto_20200831_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='job_title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
