# Generated by Django 2.2.15 on 2020-08-31 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0006_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('from_date', models.DateTimeField(blank=True, null=True)),
                ('to_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='cv',
            name='key_skills',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.AddField(
            model_name='workexperience',
            name='cv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.CV'),
        ),
        migrations.AddField(
            model_name='education',
            name='cv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.CV'),
        ),
    ]
